sudo: required
language: python
cache: pip
python:
    - "2.7"
    - "3.5"
services:
    - redis-server
install:
    - pip install --no-use-wheel lxml
    - pip install --allow-all-external -e .[test]
    - pip install coveralls
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls

deploy:
  provider: pypi
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  user: 'DaVinciDW'
  password:
      secure: "Uh+Q37dRElSmZ1YxiGv9aeg59xyCJ6dSJ87L/P1dFowHx267dX4l9xU9v3skrQSBKEIe8JjCHHT3b9D//1daObWuJ1PHQ6IdD5pp7Lwl2CkBW1TOP9MjAcZV9F0udH3X986owP8KCuwoVJglLWch+3FtI7iNpdrlcIUXlgwS4eAAfF6DmUJG5BSiHDfCdvEyLE2D13MqyXqWNixU9FQ6/5IPfEVrJsW0W0s+fUnvPNSq/R4l9oHrkhUb+2oI7OwYcCG+wXz6KOZaSn69a/sOPRI3thfc9v2FWKsz+XvBhqvNA67q2Q1kHaIn+KZnct+ZJD2tK4NrEJznf4mBliLT31YVsvYHmnsfO34+3W5G+PVdywE2j63uKAFVRzWfYRBVD1UAr0yFuCPD3Ghh7GzHFXEZm5Tltbng2BZQT82BxY4B8IPgHUMf418wRiOBKDGPSoZiHBXVtjwbWez36HOaMenXurLMaoCDWsUzl4QIJF723L5fS/z5Xq8iOoMo+5bsEIfp6BpsYh33n1zL887p03IFJHRnFlCPjdZJ7cQnBV2HTPwUNrls6c8DzaMncUj5W203k48nHm6YhspeS+uIEIrz2eCOgYD5AjjeBRsZfXlG6+DC0+O7Srnuih61xR0vJXQ9PpYCoPI5BMgQo+xwJJz2BP5IX7IpZ2HWJHFKC0E="
  on:
    branch: master
    tags: false
    repo: DarkSand/Sasila
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
